### ISSUE TITLE
How can I help and take part in your project?

### ISSUE THREAD

**Issue by DmitryAleksandrovich** [elkoniu/crocodile-carl#2]
Hello! I'd like to join your project.
A little about yourself: I'm junior C++ developer, and I don't have commercial development experience. If you have tasks (junior), I'm happy to help project. Sorry with my not very confident English:)

**Comment by elkoniu** [comment]
Hello Dmitry:)

It is a pleasure for me that you want to join my project:)
The problem is that plan for this project since beginning was, that I want to do it alone for better practice C++ and some design skills. Then I can start next game project using these experiences, and then ask some peoples to join it. This game is quite simple but feel free to ask in case of any questions:)

My suggestion is to start project like this alone to better understand all parts of software design and development, especially for game-type projects:)

One more time thank you for interesting in my project:)
